FROM apache/airflow:2.11.0
USER root
RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --upgrade numpy pyarrow pandas shapely cornac \
    apache-airflow-providers-google \
    apache-airflow-providers-snowflake